// Autogenerated from Pigeon (v5.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Book;

@interface Book : NSObject
+ (instancetype)makeWithTitle:(nullable NSString *)title
    author:(nullable NSString *)author;
@property(nonatomic, copy, nullable) NSString * title;
@property(nonatomic, copy, nullable) NSString * author;
@end

/// The codec used by BookApi.
NSObject<FlutterMessageCodec> *BookApiGetCodec(void);

@protocol BookApi
/// @return `nil` only when `error != nil`.
- (nullable NSArray<Book *> *)searchKeyword:(NSString *)keyword error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<Book *> *)findKeyword:(NSString *)keyword error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void BookApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BookApi> *_Nullable api);

/// The codec used by ColorApi.
NSObject<FlutterMessageCodec> *ColorApiGetCodec(void);

@interface ColorApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)updateColorColor:(NSNumber *)color completion:(void(^)(NSNumber *_Nullable, NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
